### PR TITLE
Update 20-update-flexget

### PR DESCRIPTION
**Pull request by planeturban**
added rarfile to base packages.

### CODE REVIEW

**Comment by cpoppema** [comment]
Hi @planeturban, thanks for your pull request. Am I right in assuming you need rarfile for the [decompress plugin](https://flexget.com/Plugins/decompress) ? I do wonder: what do you need the sqlite system package for ?

**Comment by planeturban** [comment]
Crap. Didn't think that the sqlite would be added to the pull request.. Forgot to branch. Sorry about that. So, it's not needed in this case.

And yes, rarfile is needed for decompress.

**Comment by cpoppema** [comment]
No worries. If you clean it up I'll accept the pull request. Alternatively I can add rarfile myself if you prefer and discard this pull request.

**Comment by planeturban** [comment]
Done. ;)

**Pull request merged**
